#!/usr/bin/env php
<?php

global $db;
global $oldStty;

$configSuffix = null;
if (isset($argv[1])) {
    preg_match('/^--config-(.*)$/', $argv[1], $matches);
    $configSuffix = $matches[1];
} else {
    $configSuffix = null;
}

require_once __DIR__ . '/src/init.php';

try {
    $db = init($configSuffix);

    echo "--------------- pdo-cli (c) Saki Takamachi ---------------\n\n";
    
    main();
} catch (Throwable $e) {
    die($e->getMessage()."\n");
}
