#!/usr/bin/env php
<?php

define('ROOT_DIR', __DIR__);
define('VERSION', '0.4.1');
require_once( __DIR__ . '/vendor/autoload.php');

use PDOCli\Config\Config;
use PDOCli\Console\Factory\ConsoleFactory;
use PDOCli\Database\Factory\DatabaseFactory;
use PDOCli\Lifecycle\Factory\LifecycleFactory;
use PDOCli\Option\Option;

try {
    $consoleFactory = new ConsoleFactory();
    $databaseFactory = new DatabaseFactory();
    $lifecycleFactory = new LifecycleFactory();

    $option = Option::parse(array_slice($argv, 1));

    if ($option->hasHelp()) {
        exit(Option::getHelp());
    }

    $config = Config::init()->mergeOption($option);
    $database = $databaseFactory->create($config); // TODO add style option
    $lifecycle = $lifecycleFactory->create();

    $lifecycle->initialize();
    $lifecycle->registerCleanup();

    $console = $consoleFactory->create($config, $database->getDbConfigName(), $database->getDriverName());
    $console->outputInformation();

    $console->run($database);
} catch (Throwable $e) {
    die($e->getMessage()."\n");
}
